// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.8.2")]
[assembly: AssemblyFileVersionAttribute("3.8.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.8.2";
    }
}
